spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    show-sql: true 
    properties:
      hibernate:
        hbm2ddl: 
          auto: update # 由Entity逆向生成table
        '[format_sql]': true
        '[session_factory]':
          interceptor: com.yuan.demo.interceptor.JpaInterceptor
  sql:
    init:
      schema-locations:
      - classpath:sql/table.sql
      data-locations:
      - classpath:sql/data.sql
      mode: NEVER
      
# for console sql parameters
logging:
  level:
    '[org.hibernate]': info
    '[org.hibernate.SQL]': debug
    '[org.hibernate.orm.jdbc.bind]': TRACE
    
     